version: '3.2'

services:
  rstudio:
    image: docker_patent/rstudio:1.0
    build: ./rstudio
    container_name: 'docker_patent'
    working_dir: '/home/rstudio'
    volumes:
      - ./rstudio/shared:/home/rstudio/shared
    ports: 
      - 8787:8787
    environment: 
      - DISABLE_AUTH=true
    stdin_open: true
    tty: true

